name: Deploy Modules and Configurations

on:
  workflow_dispatch:
    inputs:
      iothub_name:
        description: The name of the IoT Hub.
        required: true
        default: "iotops-hub"
      environment:
        description: "Environment to deploy to"
        required: true
        default: "iotops-demo"

env:
  deployment_id: "local-deployment-${{ github.run_id }}"
  folder_path: "deployments/"

jobs:
  deploy:
    name: Deploy Local Manifests
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Manifests
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt

          # iterate over all json files in the specified folder
          for manifest in ${{ env.deployment_id }}*.json
          do
            # extract the filename to use as the deployment id
            deployment_id=$(basename "$manifest" .json)

            echo "Deploying $manifest as $deployment_id..."

            # create or update the deployment
            az iot edge deployment create \
              --deployment-id $deployment_id \
              --hub-name ${{ github.event.inputs.iothub_name }} \
              --content "$manifest" \
              --target-condition "tags.deployment='$deployment_id'" \
              --priority 1 || \
            az iot edge deployment update \
              --deployment-id $deployment_id \
              --hub-name ${{ github.event.inputs.iothub_name }} \
              --content "$manifest" \
              --target-condition "tags.deployment='$deployment_id'" \
              --priority 1
          done
